{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}-svc"
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPorts.http }}
      protocol: {{ .Values.service.protocol }}
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
{{- end -}}
